### ISSUE TITLE
"Start with..." option.

### ISSUE THREAD

**Issue by Sena** [ipsum-community/ipsum-community.github.io#33]
Something like it!. 
<img width="465" alt="screen shot 2017-01-31 at 10 40 09" src="https://cloud.githubusercontent.com/assets/682277/22465213/c48827e2-e7a1-11e6-945d-94e321d48a6f.png">

For every single ipsum a different "start with"

**Comment by ramon-src** [comment]
Nice, it's a good idea

**Comment by Sena** [comment]
@ramon-src  How can I handle the layout?

![screen shot 2017-01-31 at 16 10 29](https://cloud.githubusercontent.com/assets/682277/22478121/d2123b72-e7cf-11e6-928d-c87a20f17187.png)

![screen shot 2017-01-31 at 16 06 51](https://cloud.githubusercontent.com/assets/682277/22478011/67b44252-e7cf-11e6-84da-d9dd041dfc69.png)
![screen shot 2017-01-31 at 16 07 01](https://cloud.githubusercontent.com/assets/682277/22478019/6b49306c-e7cf-11e6-8ddf-4deac32e768b.png)
